AWSTemplateFormatVersion: '2010-09-09'
Description: Employee Management System Infra for Prod and Test

Parameters:
  EnvType:
    Description: "The environment type (prod or test)"
    Type: String
    AllowedValues:
      - prod
      - test
    Default: test

  InstanceType:
    Description: "EC2 instance type"
    Type: String
    Default: t2.micro
  App:
    Description: Application Name
    Type: String
    Default: demo

Resources:
  # Security Group
  InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: !Sub "Security group for ${EnvType} environment"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  # EC2 Instance for App
  AppEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: !Ref InstanceType
      SecurityGroups:
        - Ref: InstanceSecurityGroup
      ImageId: 'ami-08718895af4dfa033'  # Amazon Linux 2
      KeyName: 'my-ecommerce-app-kp.pem'
      UserData:
        Fn::Base64: |
          #!/bin/bash
          yum update -y
          yum install -y httpd
          amazon-linux-extras install python3
          pip3 install flask
          systemctl enable httpd
          systemctl start httpd
          cd /var/www/html
          git clone https://github.com/your-repo/employee-management.git
          cd employee-management
          python3 app.py &
      Tags:
        - Key: Name
          Value: !Sub '${App}-${EnvType}-ec2'

  # Load Balancer for App
  AppLoadBalancer:
    Type: 'AWS::ElasticLoadBalancing::LoadBalancer'
    Properties:
      LoadBalancerName: !Sub "${EnvType}-app-loadbalancer"
      Listeners:
        - LoadBalancerPort: '80'
          InstancePort: '80'
          Protocol: 'HTTP'
      HealthCheck:
        Target: HTTP:80/
        HealthyThreshold: '3'
        UnhealthyThreshold: '5'
        Interval: '30'
        Timeout: '5'
      SecurityGroups:
        - Ref: InstanceSecurityGroup
      AvailabilityZones:
        Fn::GetAZs: ''
      Tags:
        - Key: Name
          Value: !Sub '${App}-${EnvType}-alb'

Outputs:
  InstanceId:
    Description: "EC2 Instance ID for App"
    Value: !Ref AppEC2Instance
  LoadBalancerDNS:
    Description: "DNS name of the primary load balancer"
    Value: !GetAtt AppLoadBalancer.DNSName