version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11 # Specify your Python version
    commands:
      - echo "Installing Python dependencies..."
      - pip install --upgrade pip
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo "Running pre-build steps..."
      - python -m unittest discover -s app/tests  # Optional: run unit tests if available

  build:
    commands:
      - echo "Building the Flask application..."
      - python app/app.py  # Ensure this runs correctly as part of the build

  post_build:
    commands:
      - echo "Build completed successfully!"

artifacts:
  files:
    - '**/*'  # Include all files in the output artifact
  discard-paths: yes
