version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - ls
      - cd devops/_aws/_codebuild/sample-python-app/
      - pip install -r requirements.txt
  build:
    commands:
      - echo Building the application...
      - ls
      - cd devops/_aws/_codebuild/sample-python-app/
      - python hello.py

artifacts:
  files:
    - '**/*'
  discard-paths: yes