---
- name: Install Nginx on web servers
  hosts: web_servers
  become: yes

  # sudo apt update
  # sudo apt install nginx
  # sudo systemctl staus nginx
  tasks:
    - name: Update package cache
      apt:
        update_cache: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Ensure Nginx is running
      service:
        name: nginx
        state: started
        enabled: yes

# - name: Create a folder on web servers
#   hosts: web_servers
#   become: yes
#   tasks:
#     - name: Create /var/www/html directory
#       file:
#         path: /var/www/html
#         state: directory
#         mode: '0755'

